FROM golang:latest
WORKDIR /Code
ENV GO111MODULE=on \
    GOPROXY=https://goproxy.cn,direct

# cache deps before building and copying source so that we don't need to re-download as much
# and so that source changes don't invalidate our downloaded layer

# src code
COPY . .
RUN go mod tidy
RUN go build ./src/Web
#RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64  go build -o ./src/Web
EXPOSE 8080